# Generated by Django 6.0.1 on 2026-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=30)),
                ('asiento', models.IntegerField(default=0)),
                ('vendido', models.BooleanField(default=True)),
            ],
        ),
    ]
