# Generated by Django 6.0.1 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='asiento',
            field=models.CharField(max_length=3),
        ),
    ]
