# Generated by Django 6.0.1 on 2026-01-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_alter_entrada_asiento'),
        ('funcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcion.funcion'),
        ),
    ]
