# Generated by Django 6.0.1 on 2026-01-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_horario', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=30)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.pelicula')),
            ],
        ),
    ]
