# Generated by Django 6.0.1 on 2026-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
