# Generated by Django 6.0.1 on 2026-02-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='Silvester Stallone', max_length=100),
        ),
    ]
